### ISSUE TITLE
File Manager bei pageTree

### ISSUE THREAD

**Issue by codepiX-dev** [menatwork/MultiColumnWizard#158]
Hallo, 

mir ist aufgefallen, dass bei der Verwendung des pageTree als inputType mit dem MCW noch eine Verlinkung zum File Manager generiert wird. Diese funktioniert nicht mehr.

Diese verweist auf /contao/files.php.

$xlabel .= ' a href="' . $strContaoPrefix . 'files.php' . $path . '" title="' . specialchars($GLOBALS['TL_LANG']['MSC']['fileManager']) . '" rel="lightbox[files 765 80%]">' . $this->generateImage('filemanager.gif', $GLOBALS['TL_LANG']['MSC']['fileManager'], 'style="vertical-align:text-bottom;"') . '</a';

VG
Patrick

**Comment by zonky2** [comment]
Fixed in MCW-bundle https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/25
