### ISSUE TITLE
fileTree and pageTree widgets don't work in Contao 3.3

### ISSUE THREAD

**Issue by ausi** [menatwork/MultiColumnWizard#160]
MultiColumnWizard field with the following configuration

``` php
'inputType' => 'multiColumnWizard',
'eval' => array(
    'columnFields' => array(
        'my_file' => array(
            'inputType' => 'fileTree',
            'eval' => array(
                'multiple' => true,
                'fieldType' => 'checkbox',
            ),
        ),
        'my_page' => array(
            'inputType' => 'pageTree',
            'eval' => array(
                'multiple' => true,
                'fieldType' => 'checkbox',
            ),
        ),
    ),
),
'sql'=> 'blob NULL',
```

doesn't work correctly: 
1. In the file manager no file or folder can be selected
2. In the page tree only single pages are selectable

It might be related to one of these commits: 
- https://github.com/contao/core/commit/b783205a6dd9e792b13b6ca026f8023823eb1b82
- https://github.com/contao/core/commit/3227b43e1b1cc8ee058e6b25790a5bdd66a31cc4
- https://github.com/contao/core/commit/39275e2b82b4ecd9f6ef5ccc6c808e461f15a60e

**Comment by zonky2** [comment]
check with MCW 3.3.12

* Filepicker works
* Pagepicker works but only with single select per radio

```
            'mcw_pagetree' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_pagetree'],
                'exclude'       => true,
                'inputType'     => 'pageTree',
                'eval'          => array
                    (
                    'fieldType' => 'checkbox',
                    'multiple'  => true
                    )
                ),

            'mcw_filetree' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_filetree'],
                'exclude'       => true,
                'inputType'     => 'fileTree',
                'eval'          => array
                    (
                    'fieldType'  => 'checkbox', // 'checkbox'|'radio'
                    'files'      => true,
                    'filesOnly'  => true,
                    'multiple'   => true, // true|false
                    'extensions' => $GLOBALS['TL_CONFIG']['uploadTypes']
                    )
                ),
```

![shot374](https://user-images.githubusercontent.com/1045318/31356830-bd312142-ad3f-11e7-9717-f887e4a28e3c.jpg)
![shot375](https://user-images.githubusercontent.com/1045318/31356832-c20d1e32-ad3f-11e7-841c-0d1283abf899.jpg)
![shot376](https://user-images.githubusercontent.com/1045318/31356835-c5560d56-ad3f-11e7-9e87-966536cb66ae.jpg)

**Comment by zonky2** [comment]
pagePicker fixed with https://github.com/menatwork/MultiColumnWizard/pull/235
