### ISSUE TITLE
Import/Export der Werte

### ISSUE THREAD

**Issue by xantippe** [menatwork/MultiColumnWizard#165]
Hi,

wäre es möglich, für den MCW eine Import/Export-Funktion einzubauen - das geht natürlich nur bei passenden Typ-Werten. 

Gerade wenn viele Werte eingetragen werden müssen, wäre ein CSV-Import (oder XML) prima bzw. auch die Übertragung von einem MCW-Widget zu einem anderen.

Gruss

**Comment by davidmaack** [comment]
Nein, der MCW ist ja nur ein Widget. Ein Importer / Exporter müsste doch immer einen kompletten Datensatz befüllen und die richtigen Werte in die Datenbank speichern. Damit der MCW Importierte Daten anzeigen kann, muss ein Import-Skript doch nur das serialisierte Array von MCW wegspeichern (welches natürlich von der MCW Config abhängt).

Wenn du viele neue Datensätze mit ähnlichem Inhalt anlegen müsst, kopiere dir doch immer einen und mach dann nur die Änderungen. Etwas schneller als mit der Kopieren-Funktion von Contao geht es mit dem Clipboard: https://contao.org/de/extension-list/view/clipboard.html
