### ISSUE TITLE
FR: neuer Button "Auge" und up/down per D&D

### ISSUE THREAD

**Issue by zonky2** [menatwork/MultiColumnWizard#171]
Hi,

könnten die Buttons nicht mit den nun aktuell bei Contao üblichen Buttons zum Verschieben der Position ausgetauscht werden 

und

es wäre schön, das "Auge" als neuen Button dabei zu haben

z.B. wie beim Layout-Builder
![fireshot screen capture 103 - themes music academy seitenlayouts layout id 1 bearbeiten - contao open source cms 3_2 - dev_e-spin_de_contao_main_php_do themes table tl_layout act edit id 1](https://cloud.githubusercontent.com/assets/1045318/5487179/f01f219a-86ae-11e4-83e5-ba2a4296000d.jpg)

**Comment by tognit** [comment]
+1

Das mit der "dragAndDrop" Sortierung wäre cool. Es gibt ja schon ein "branch" dazu.

**Comment by zonky2** [comment]
D&D => https://github.com/menatwork/MultiColumnWizard/pull/219
