### ISSUE TITLE
Datepicker funktioniert im MultiColumnWizard nicht

### ISSUE THREAD

**Issue by Total-Reality** [menatwork/MultiColumnWizard#173]
Kann man einfach testen, indem man mal die Erweiterung calendarextended installiert. Der Datepicker wird einfach an das Ende des Bodys geschmissen.

**Comment by davidmaack** [comment]
Und wenn du uns noch verraten würdest welche Version des MCW du installiert hast und welche Contao-Version das betrifft, würde ich das sogar mal nachstellen :)

**Comment by Total-Reality** [comment]
Hi David,

sorry, ich dachte ich hätte die neuesten Versionen, daher habe ich es nicht erwähnt. 
Das komische ist erst mal, ich hatte von MCW die 3.1.0 installiert und er hat mir im extension_repository gar nicht angezeigt, dass es bereits eine neuere Version gibt. Ich habe jetzt MCW  3.2.3 installiert.
Aber auch hier tritt das Problem auf.

Zudem ist Contao mit der Version 3.4.3 installiert.

**Comment by dtomasi** [comment]
Habe das gleiche Problem:

Contao 3.4.4
Composer-Client
menatwork/contao-multicolumnwizard 3.3.0
contao-legacy/calendar_extended 3.2.0.9118

siehe auch hier: https://github.com/kmielke/calendar_extended/issues/20 
und https://github.com/kmielke/calendar_extended/issues/22

**Comment by dtomasi** [comment]
@davidmaack Danke für de Merge... Das Issue kann denke ich geschlossen werden :+1:

**Comment by Total-Reality** [comment]
Bei mir ist die Erweiterung im ER nicht in Version 3.3.0 verfügbar - Welchen Sinn ergibt das bitte?

**Comment by davidmaack** [comment]
Hat wohl noch keiner da vermisst :). Wenn ich von Sven das Feedback zu seinem Issue bekommen habe, tagge ich mal die 3.3.1 und pack das dann auch ins ER.

**Comment by BugBuster1701** [comment]
:+1:

**Comment by baumannsven** [comment]
habe es geprüft bitte nutze den neuen pull #180
