### ISSUE TITLE
TinyMCE läuft nicht (Contao 3.4.4)

### ISSUE THREAD

**Issue by Fuzzyma** [menatwork/MultiColumnWizard#175]
Ich versuche diesen Wizard mit Contao 3.4.4 zu benutzen. Funktioniert auch alles soweit (abgesehen von den verschwindenen Select-feldern, die man aber wieder zu sehen bekommt wenn man `'eval' => array('class' => 'tl_chosen')` benutzt).  
Allerdings will tinyMCE kein Stück.

Das tinymce-javascript wird auch nirgends geladen.
Interessant ist allerdings, dass es auch nicht funktioniert, wenn ich vorher über contao ein funktionierendes tinymce-feld einfüge und `tinyMCE.execCommand` laut Konsole auch definiert ist

Hat irgendjemand eine Idee woran das liegen könnte?

**EDIT:** Contao 3.4.4 nutzt den tinyMCE in der Version 4
Die genaue Version ist `4.1.6 (2014-10-08)`

**Comment by Fuzzyma** [comment]
Ok - in contao 3.4.4 wird tinyMCE asyncron nachgeladen - aber erst wenn es gebraucht wird.
Das führt dazu, dass bei Nutzung von tinyMCE mit MultiColumnWizard

 - tinymce nicht definiert ist, weil es noch von keinem anderem Formular vorher geladen wurde oder aber
 - tinymce noch nicht fertig geladen ist, wenn tinyMCE.execCommand aufgerufen wird

Außerdem benutzt MultiColumnWizard noch den command `mceAddControl`, der in tinyMCE4 nicht mehr existiert. Stattdessen kann man `mceAddEditor` benutzen, der genau das gleiche macht.

Contao selbst löst das Problem in dem das Script, welches tinyMCE lädt, die Methode `tinyMCE.init()` schonmal definiert, damit diese dann genutzt werden kann.

Es sollte also überlegt werden, ob man zum initialisieren der tinyMCE-Instanzen nicht auf `init` anstatt `execCommand` zurückgreifen sollte

**Comment by zonky2** [comment]
getestet mit Contao 3.5.28 und MCW 3.3.12

![shot368](https://user-images.githubusercontent.com/1045318/31284413-bdbdb0aa-aab8-11e7-9bb5-26c84e1f3650.jpg)

**Comment by Total-Reality** [comment]
TinyMCE an sich geht, aber nicht wenn man die Felder dupliziert... Dann ist der duplizierte Text im neuen TinyMCE Fenster nicht sichtbar.
Man kann auch keine Buttons betätigen. Erst wenn man die Seite speichert, kann man weiter arbeiten. Also scheinbar erkennt er das neue Feld erst nach dem Speichern (und dem erzwungenen Reload dadurch).
Das Phänoment ist so ähnlich wie bei den Selectboxen quasi...

Getestet mit Contao 3.5.31 und MCW 3.3.6 und auch mit dem neuesten MCW 3.3.12 geht es nicht.
