### ISSUE TITLE
styled_select container is removed on adding new row

### ISSUE THREAD

**Issue by dtomasi** [menatwork/MultiColumnWizard#178]
![bildschirmfoto 2015-04-21 um 08 59 00](https://cloud.githubusercontent.com/assets/1616726/7247043/1aeff5cc-e805-11e4-9d9e-d08b99bd4f7d.png)

Wie im Screenshot zu sehen, verschwindet der div-container styled_select wenn man per "+" eine neue Zeile hinzufügt. 

Contao 3.4.5
MCW 3.3.0

**Comment by dtomasi** [comment]
Die betreffende Zeile schein diese zu sein: https://github.com/upcom-ch/MultiColumnWizard/blob/master/system/modules/multicolumnwizard/html/js/multicolumnwizard_be_src.js#L451

Kann mir jemand sagen, aus welchem Grund bei einem BUILD > 3 das Item entfernt wird?

**Comment by davidmaack** [comment]
Solche Fragen sind beim MCW echt die falschen :). Ich denke, dass deine Abfrage in deinem RP da eigentlich gewünschte sein sollte. Wird wohl ein Ergebnis aus zu wenig Kaffe, nervenden PMs/Kollegen und zu wenig Zeit gewesen sein;)

**Comment by dtomasi** [comment]
@davidmaack Klar, war völlig off-topic. @Toflar konnte mir das aber beantworten... 
Denke so sollte das aber passen. :smile:
