### ISSUE TITLE
Version 3.3.1 installiert falsch

### ISSUE THREAD

**Issue by do-while** [menatwork/MultiColumnWizard#181]
Die aktuelle Version 3.3.1 aus dem ER2 installiert/aktualisiert den MultiColumnWizard falsch.
In /system/modules wird ein Verzzeichnis MultiCoulmnWizard angelegt und dort hinein als TL_ROOT noch einmal installiert, da das Verzeichnis bis auf Groß/Kleinschreibung identisch mit dem richten multicolumnwizard-Verzeichnis ist, wird die Erweiterung komplett ignoriert.

Erweiterung steht dann in /system/modules/MultiColumnwizard/system/modules/multicolumnwizard/...

Lösung für's Erste ist zurück auf Version 3.2.3 zu gehen.

**Comment by discordier** [comment]
yop, wurde falsch ins ER importiert.
vgl: https://contao.org/de/extension-list/fileview/MultiColumnWizard.de.html?

**Comment by davidmaack** [comment]
Dateien wurden neu importiert.
