### ISSUE TITLE
[Contao 3.5] Uncaught ReferenceError: parseContaoVersion is not defined

### ISSUE THREAD

**Issue by qzminski** [menatwork/MultiColumnWizard#183]
Where did you get that method from? I could not find it neither in your extension nor in Contao core. This causes the error in Contao 3.5.

https://github.com/menatwork/MultiColumnWizard/blob/dev/system/modules/multicolumnwizard/html/js/multicolumnwizard_be_src.js#L446

**Comment by Toflar** [comment]
I guess this is just a leftover as comparison is done further down using `versionCompare()` and `var version` is never used anyway?

**Comment by qzminski** [comment]
Can you release a new patch version with this fix please?
