### ISSUE TITLE
MCW shows Contao version in backend login and Install Tool

### ISSUE THREAD

**Issue by fritzmg** [menatwork/MultiColumnWizard#184]
When MCW is installed, the exact Contao version is visible in the source code of the backend login and the Install Tool via the body class, due to the usage of the `parseTemplate` hook

* https://github.com/menatwork/MultiColumnWizard/blob/3.3.4/system/modules/multicolumnwizard/config/config.php#L48
* https://github.com/menatwork/MultiColumnWizard/blob/3.3.4/system/modules/multicolumnwizard/MultiColumnWizardHelper.php#L32
* https://github.com/contao/core/blob/3.2.12/system/modules/core/templates/backend/be_login.html5#L34
* https://github.com/contao/core/blob/3.2.12/system/modules/core/templates/backend/be_install.html5#L27

Imho this poses a slight security issue, since the exact Contao version would otherwise not be accessible from the outside. Maybe something like this should be added:
```php
if ($objTemplate->getName() != 'be_login' && $objTemplate->getName() != 'be_install')
    …
```
Though I haven't checked if that covers all the publicly available backend templates.

Or, alternatively, add
```php
if (TL_USER_LOGGED_IN)
```
to the config.php before the hook is inserted.

**Comment by fritzmg** [comment]
Bei einem Penetrationstest einer externen Firma bei einem Kunden wurde das wieder mal beanstandet... könnte man das nicht schnell beheben?

**Comment by BugBuster1701** [comment]
Das wird im Backend in der Javascript Datei für einen Vergleich verwendet, ob Contao >= 3.2.3 ist.
Ich denke mal, wenn man MCW ab 3.3 definiert, könnte der Vergleich und somit die Setzung sogar raus, falls ich nichts übersehen habe.

**Comment by fritzmg** [comment]
Backend ist ja ok. Es geht ja nur um die Backend __Login__ Seite. Dort wird das JavaScript nicht benötigt.

**Comment by BugBuster1701** [comment]
Achso, ja das würde auch reichen das da raus zunehmen.

**Comment by davidmaack** [comment]
Fixed by @fritzmg with  https://github.com/menatwork/MultiColumnWizard/pull/213. Thanks for the PR!

**Comment by fritzmg** [comment]
Sehr gut, bitte und danke :). Ich hoffe ein neuer Release Tag lässt auch nicht lange auf sich warten ;)
