### ISSUE TITLE
tl_select Breite standardmäßig zu klein

### ISSUE THREAD

**Issue by garyee** [menatwork/MultiColumnWizard#189]
Hallo,

die tl_select div's sind standardmäßig auf width: auto (multicolumnwizard.css Zeile 9) gesetzt, was aber irgendwie bewirkt, dass das Select Feld immer(!) zu klein ist. Das ist mir jetzt schon bei mehreren Installationen "passiert" ist.
Ich weiß nicht ob es dafür eine Lösung gibt, aber es wäre irgendwie gut, wenn die Select-Inputs minimal so breit sind wie der längste Text der Optionen.
Beispiel: ![unbenannt](https://cloud.githubusercontent.com/assets/5537949/8565897/10b3d258-255a-11e5-8a00-b8a3c152c6f0.png)

**Comment by zonky2** [comment]
@garyee ist das bei "aktuellen" Browsern auch noch so?

**Comment by zonky2** [comment]
checked with 3.3.12

Die eingegebene Elementbreite überschreibt das auto - auch bei auto ist bei aktuellen Browsern die Selectbox groß genug
