### ISSUE TITLE
Callbacks kaputt

### ISSUE THREAD

**Issue by garyee** [menatwork/MultiColumnWizard#191]
Hallo,

ich hätte gern die JS Callbacks benutzt aber aus irgend einem Grund verhalten die sich komisch.
Mein Testfunktion:

```
window.addEvent("load", function() {
                       var mcw= window['MCW_changes'];
                        mcw.addOperationClickCallback("copy",copyCallback);
                 });

                 var copyCallback = function(el, row){
                                     console.log(\"test\");
                 }

```

Wenn ich eine Zeile dupliziere, kommt der console.log erst beim zweiten Mal (wenn die duplizierte Zeile nochmal dupliziert wird)
Und dann kommt gleich ein Fehler:
**self.updateFields is not a function** (im js zeile 123)

**Comment by Toflar** [comment]
Die Callbacks kannst du vergessen. Die funktionieren nicht. Ich hab vor ewiger Zeit mal einen kompletten Rewrite gemacht, der aber nie gemerged wurde (https://github.com/menatwork/MultiColumnWizard/pull/88/files).

**Comment by garyee** [comment]
okay ... gut zu wissen, gibt es Hoffnung das der PR vielleicht doch irgendwann mal gemerged wird?

**Comment by Toflar** [comment]
Nein, die gibt es definitiv nicht. Eher, dass eine Alternative zum MCW kommt^^

**Comment by garyee** [comment]
Das wäre sehr gut... irgendwie kommt man nicht um den MCW herum wenn man Erweiterungen programmiert, zum. für die komplexeren Sachen. ( außer wenn man es selber macht ...)

**Comment by zonky2** [comment]
in Contao 4.x wird es sicher eine Alternative geben - @garyee kann ich das Ticket schließen?

**Comment by garyee** [comment]
Ja mach mal
