### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by CodeAlDente** [menatwork/MultiColumnWizard#192]
There seems to be a conflict with duplicated files(?). Because everytime I update my packages, I get the following error lines:

**Generating autoload files**
> **Warning: Ambiguous class resolution**, "MenAtWork\MultiColumnWizard\Event\GetOptionsEvent" **was found in both** "~/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/src/Event/**GetOptionsEvent.php**" and "~/composer/vendor/contao/core/system/modules/multicolumnwizard/src/Event/GetOptionsEvent.php", the first will be used.
>
> **Warning: Ambiguous class resolution**, "MultiColumnWizard" was found in both "~/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/**MultiColumnWizard.php**" and "~/composer/vendor/contao/core/system/modules/multicolumnwizard/MultiColumnWizard.php", the first will be used.
>
> **Warning: Ambiguous class resolution**, "MultiColumnWizardHelper" was found in both "~/composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/**MultiColumnWizardHelper.php**" and "~/composer/vendor/contao/core/system/modules/multicolumnwizard/MultiColumnWizardHelper.php", the first will be used.

**Comment by discordier** [comment]
you have been bitten by https://github.com/contao-community-alliance/composer-plugin/issues/44

**Comment by stefanheimes** [comment]
Should be fixed now. See contao-community-alliance/composer-plugin#44.
