### ISSUE TITLE
[3.3.3] PHP 7 Kompatibilität

### ISSUE THREAD

**Issue by baumisimon** [menatwork/MultiColumnWizard#193]
Unter PHP 7 (final) kommt immer wieder folgende Fehlermeldung:
```
Fatal error: Uncaught exception Error with message Function name must be a string thrown in system/modules/multicolumnwizard/MultiColumnWizard.php on line 866

#0 system/modules/multicolumnwizard/MultiColumnWizard.php(479): MultiColumnWizard->initializeWidget(Array, 0, 'name', 'type')
#1 system/modules/core/library/Contao/Widget.php(684): MultiColumnWizard->generate()
#2 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/homepages/xx/x...')
#4 system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#5 system/modules/core/classes/DataContainer.php(546): Contao\Widget->parse()
#6 system/modules/core/drivers/DC_Table.php(1945): Contao\DataContainer->row('{name_legend},n...')
...
```
Vermutlich liegt der Grund dafür hier: http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling

**Comment by css-umsetzung** [comment]
Hallo......tut sich hier irgendwann etwas?

**Comment by davidmaack** [comment]
Ja, irgendwann :D. Da wir noch keinen Zeitplan für die Umstellung auf PHP7 haben, kann ich hierzu echt noch nix sagen. Ich kann ja den Fehler nicht einmal nachstellen und Zeile 866 ist im aktuellen Branch ein "}". Wir könnten jetzt also nur raten wo genau überall uns das alte Variablenhandling auf die Füße fällt.

Solltest du da weiter sein -> PRs sind hier natürlich jederzeit willkommen ;)

**Comment by BugBuster1701** [comment]
Hab  mal gescannt den aktuellen Master Branch
```
$ php7cc ./

File: /system/modules/multicolumnwizard/MultiColumnWizard.php
> Line 268: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}($varValue, $this);
> Line 268: Indirect variable, property or method access
    $this->{$callback[0]};
> Line 385: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}(serialize($this->varValue), $dc);
> Line 385: Indirect variable, property or method access
    $this->{$callback[0]};
> Line 621: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}($dc, $objWidget);
> Line 621: Indirect variable, property or method access
    $this->{$callback[0]};
> Line 889: Indirect variable, property or method access
    $this->{$arrField['input_field_callback'][0]};
> Line 894: Indirect variable, property or method access
    $this->{$arrField['input_field_callback'][0]}->{$arrField['input_field_callback'][1]}($this, $xlabel);
> Line 894: Indirect variable, property or method access
    $this->{$arrField['input_field_callback'][0]};
> Line 946: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}($varValue, $this);
> Line 946: Indirect variable, property or method access
    $this->{$callback[0]};
> Line 998: Indirect variable, property or method access
    static::importStatic($arrCallback[0])->{$arrCallback[1]}($this);
```

Dort könnten Probleme aufkommen.

**Comment by css-umsetzung** [comment]
Ja, das ist ein Problem das so ziemlich alle Plugins betrifft.

**Comment by my-om** [comment]
Hallo,
bei mir ist das Problem auch aufgetreten. Gibt es jetzt eine Lösung?

**Comment by davidmaack** [comment]
Du könntest mal den aktuellen Master-Branch ausprobieren, das sind schon PHP7 Anpassungen drin. Ich habe das nur noch nicht selber ausprobiert oder ein Fedback bekommen ob das wirklich ohne Fehler läuft

Ansonsten probiere ich das nächste Woche mal aus.

**Comment by davidmaack** [comment]
Version 3.3.6 ist mit PHP7 kompatibel.

**Comment by BugBuster1701** [comment]
@davidmaack  Da wurde eine Zeile übersehen:
[MultiColumnWizard.php#L889](https://github.com/menatwork/MultiColumnWizard/blob/master/system/modules/multicolumnwizard/MultiColumnWizard.php#L889)

`if (!is_object($this->$arrField['input_field_callback'][0]))`
ändern in 
`if (!is_object($this->{$arrField['input_field_callback'][0]}))`
