### ISSUE TITLE
Two errors with colorpicker  in MultiColumnWizard.php

### ISSUE THREAD

**Issue by Paddy0174** [menatwork/MultiColumnWizard#197]
Found another two errors with the colorpicker

1.) the ID for the corresponding field is not set correctly in the MooRainbow script (lines 579 to 590)
change:

``` php
<script>
                window.addEvent("domready", function() {
                  new MooRainbow("moo_' . $objWidget->id . '", {
                    id: "ctrl_' . $objWidget->id . '",
                    startColor: ((cl = $("ctrl_' . $objWidget->id . '").value.hexToRgb(true)) ? cl : [255, 0, 0]),
                    imgPath: "assets/mootools/colorpicker/' . $GLOBALS['TL_ASSETS']['COLORPICKER'] . '/images/",
                    onComplete: function(color) {
                      $("ctrl_' . $objWidget->id . '").value = color.hex.replace("#", "");
                    }
                  });
                });
              </script>';
```

to

``` php
<script>
                window.addEvent("domready", function() {
                  new MooRainbow("moo_' . $objWidget->id . '", {
                    id: "ctrl_' . $objWidget->id . '_0",
                    startColor: ((cl = $("ctrl_' . $objWidget->id . '_0").value.hexToRgb(true)) ? cl : [255, 0, 0]),
                    imgPath: "assets/mootools/colorpicker/' . $GLOBALS['TL_ASSETS']['COLORPICKER'] . '/images/",
                    onComplete: function(color) {
                      $("ctrl_' . $objWidget->id . '_0").value = color.hex.replace("#", "");
                    }
                  });
                });
              </script>';
```

adds "_0" in lines 582, 583, 586 to the ID.

2.) the image for the colorpicker is not aligned to the field when tableLess is set to false, because there is the class "inline" missing in line 1122. Not sure, if this fits all cases, just tried it with the colorpicker only.
change

``` php
                $return .= '<td' . ($itemValue['valign'] != '' ? ' valign="' . $itemValue['valign'] . '"' : '') . ($itemValue['tl_class'] != '' ? ' class="' . $itemValue['tl_class'] . '"' : '') . '>' . $itemValue['entry'] . '</td>';
```

to

``` php
                $return .= '<td' . ($itemValue['valign'] != '' ? ' valign="' . $itemValue['valign'] . '"' : '') . ($itemValue['tl_class'] != '' ? ' class="' . $itemValue['tl_class'] . ' inline"' : '') . '>' . $itemValue['entry'] . '</td>';
```

Please check the second one, as I'm not entirely sure about other cases then the colorpicker.
Thanks a lot! :)

**Comment by davidmaack** [comment]
Can you post your DCA of the color-picker field? It's working here without your changes.
```php
'ts_extension' => array
     (
         'label' => &$GLOBALS['TL_LANG']['tl_page']['ts_extension'],
         'inputType' => 'text',
         'eval' => array('style' => 'width:75px', 'size'=>1, 'colorpicker'=>true, 'isHexColor'=>true, 'decodeEntities'=>true, 'tl_class'=>'wizard'),
     ),
```

**Comment by Paddy0174** [comment]
Sure! :)
Just tested both things again, didn't have any luck.
`'tfl_groupsPlaceAndColor' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tfl_settings']['tfl_groupsPlaceAndColor'],
			'inputType'               => 'multiColumnWizard',
			'eval'                    => array('mandatory'=>true, 'columnFields' => array(
												
												'tfl_gpac_color' => array(
													'label' => &$GLOBALS['TL_LANG']['tfl_settings']['tfl_gpac_color'],
													'inputType' => 'text',
													'eval' => array('style' => 'width:200px', 'maxlength'=>6, 'multiple' => true, 'size'=>1, 'colorpicker'=>true, 'isHexColor'=>true, 'decodeEntities'=>true, 'tl_class' => 'wizard')
												),
												'tfl_gpac_start' => array(
													'label' => &$GLOBALS['TL_LANG']['tfl_settings']['tfl_gpac_start'],
													'inputType' => 'text',
													'eval' => array('style' => 'width:100px', 'rgxp' => 'natural', 'mandatory'=>true)
												),
												'tfl_gpac_end' => array(
													'label' => &$GLOBALS['TL_LANG']['tfl_settings']['tfl_gpac_end'],
													'inputType' => 'text',
													'eval' => array('style' => 'width:100px', 'rgxp' => 'natural', 'mandatory'=>true)
												),
											)
										)
		),`
Tbh, without the "multiple" it doesn't work, so I'm not entirely sure...

**Comment by Paddy0174** [comment]
Seems to be a new version of MCW, still have the exact same issues. :(

**Comment by zonky2** [comment]
Fixed in https://github.com/menatwork/MultiColumnWizard/pull/231
