### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by aschempp** [menatwork/MultiColumnWizard#204]
can you please tag a new version so MCW is available for Contao 4?

**Comment by davidmaack** [comment]
Has anyone tested the last patches? I Don´t have a PHP7-System right now to give it a try....

**Comment by Toflar** [comment]
How is Contao 4 related to PHP7?

**Comment by davidmaack** [comment]
It´s not, github just sorted the last commits in the wrong order so I read that the first new commit was a PHP7-patch :)

3.3.4 with the updated composer.json is release without any PHP7-patches

**Comment by Fuzzyma** [comment]
How did you get this to work in contao 4?
I run a normal install with composer (`composer require...`) and it installed it and linked it. Still when I use multiColumnWizard as inputType it just does nothing.

My DCA looks like this:

```
        'texts' => [
            'label'                   => &$GLOBALS['TL_LANG']['tl_products']['texts'],
            'inputType'               => 'multiColumnWizard',
            'sql'                     => "blob NULL",
            'eval'                    => [
                'columnFields' => [
                    'name'  => [
                        'label'     => &$GLOBALS['TL_LANG']['tl_products']['texts_name'],
                        'inputType' => 'text'
                    ]
                ]
            ]
        ],
```

**Comment by aschempp** [comment]
MCW works perfectly fine for me in Contao 4, but this ticket is only about installation (not usage). Better create a new issue or use the community forums for general questions.
