### ISSUE TITLE
[3.3.3] rgxp digit geht nicht

### ISSUE THREAD

**Issue by Total-Reality** [menatwork/MultiColumnWizard#205]
Hi,
leider funktioniert in Version 3.3.3 (Contao 3.5.12) diese Angabe von mir hier nicht richtig:
'eval' => array('rgxp'=>'digit', 'style'=>'width:50px')

Ich kann in das Feld dann nicht nur Zahlen wie 1 oder 2, sondern alles mögliche eintragen, auch Buchstaben etc. komplett ohne Zahlen.

Zudem wäre es interessant, ob man verhindern kann, dass Kommagetrennte Werte eingegeben werden.

Viele Grüße
Christian

**Comment by davidmaack** [comment]
Poste mal bitte die DCA-Config von dem ganzen Feld, dann versuch ich das mal nach zu stellen

**Comment by Total-Reality** [comment]
'min' => array(
				'label'							=> &$GLOBALS['TL_LANG']['blabla']['min'],
				'exclude'						=> true,
				'inputType'					=> 'text',
				'eval'							=> array('rgxp'=>'digit', 'maxlength'=>5, 'style'=>'width:50px')
			),

**Comment by zonky2** [comment]
Test mit 3.3.12

![shot367](https://user-images.githubusercontent.com/1045318/31282285-69196af4-aab2-11e7-8ef0-fb92e0ad07de.jpg)

**Comment by Total-Reality** [comment]
Geht leider immer noch nicht. Getestet mit Version 3.4.9
Screen: Alle Felder mit rgxp => digit ausgestattet. Btw. auch minval greift nicht.

![mcw-amount](https://user-images.githubusercontent.com/5235894/104539239-65fc3580-561d-11eb-9e1d-13dacfc72f51.PNG)

**Comment by zonky2** [comment]
poste mal Deinen gesamten Code sowie Version von Contao

**Comment by Total-Reality** [comment]
Simples Beispiel Siehe hier https://github.com/menatwork/MultiColumnWizard/issues/205#issuecomment-231595237
Contao 4.9.9

Mir ist jetzt allerdings aufgefallen, dass es bei dir wahrscheinlich funktioniert, weil du wahrscheinlich im eval des DCA-Feldes mit "columnFields" arbeitest und direkt alles dort rein knallst und ich aber der Übersichtlichkeit halber mit "columnsCallback".

**Comment by zonky2** [comment]
Contao 4.9.10
MCW 3.4.9

```
/* Fields */
$GLOBALS['TL_DCA'][$strTblName]['fields']['mcwtest'] =
    [
        'exclude'   => true,
        'inputType' => 'multiColumnWizard',
        'eval'      => [
            'minCount'     => 2,
            'maxCount'     => 4,
            'columnFields' => [
                'min' => [
                    'label'     => 'Min',
                    'exclude'   => true,
                    'inputType' => 'text',
                    'eval'      => ['rgxp' => 'digit', 'maxlength' => 5, 'style' => 'width:50px']
                ],
            ],
        ],
        'sql'       => "blob NULL"
    ];
```

![FireShot Pro Webpage Screenshot #205 - 'Articles › MCW-Test › Content elements › Edit content element ID 26 I mm220_dev_metamodel_me' - mm](https://user-images.githubusercontent.com/1045318/104695983-d5515280-570d-11eb-86f4-c5791a6e3440.jpg)

works fine

**Comment by Total-Reality** [comment]
Du arbeitest mit columnFields. Das will ich aber nicht. Ihr bietet doch die Funktion columnsCallback - Warum geht es da nicht? Ich versteh den Unterschied bzw. die Logik nicht?

Ich denke, dass so einige hier geschildere Probleme / issues darauf beruhen, dass die Leute ebenfalls die columsCallback Funktion benutzen.

**Comment by zonky2** [comment]
solange Du Deine Code nicht postest, teste ich NIX!

**Comment by Total-Reality** [comment]
Kommentar geändert, da ja nur noch das Bundle unterstützt wird. Hab jetzt ein neues Ticket hier aufgemacht: https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/98
