### ISSUE TITLE
wrong compatibility information in ER2

### ISSUE THREAD

**Issue by fritzmg** [menatwork/MultiColumnWizard#209]
This extension is not compatible with Contao 2 anymore since version `3.3.4`. While this change is correctly reflected in the `composer.json`, [the extension repository](https://contao.org/de/erweiterungsliste/view/MultiColumnWizard.de.html) still lists version `3.3.6` to be compatible with Contao `>=2.11.0`.

(noticed due to this thread: https://community.contao.org/de/showthread.php?63653-contao-2-11-17-Backend-funktioniert-nicht-mehr&p=417726&viewfull=1#post417726)

**Comment by davidmaack** [comment]
Updated the dependencies in the ER for version 3.3.6
