### ISSUE TITLE
DateFormat Confusion with english pages

### ISSUE THREAD

**Issue by garyee** [menatwork/MultiColumnWizard#212]
Hi,

so I'm using the MCW for the FE on a site that has multiple pagetrees (one english, on german).
The two trees have different dateformats configured in their settings. (de: d.m.Y, en: Y-m-d)
When people used the (mootools-) datepicker, it outputed the "german format" even on the english page but then came naturally came the error that it is not the right format. (datepicker output: d.m.Y, site setting: Y-m-d)

I found the reason and will link the PR.

**Comment by zonky2** [comment]
fixed with #211
