### ISSUE TITLE
Update via composer erzeugt Fehler

### ISSUE THREAD

**Issue by planepix** [menatwork/MultiColumnWizard#224]
Hallo,

Update einer 4.4.6 Installation und Contao Manager liefert einen Fehler.
Auch das Update via Konsole erzeugt folgenden Fehler:

[RuntimeException]
  "/xxx/system/modules/multicolumnwizard" is not a link to "/xxx/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard" (expected "/xxx/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard" but got "/xxx/system/modules/multicolumnwizard")

Der Ordner /cache/prod/ wurde gelöscht.
Der Fehler wird auch danach angezeigt.

Aufruf des Composers: /usr/local/php71/bin/php composer.phar update
Hosting: netcup

**Comment by planepix** [comment]
Update:
Geholfen hat, in den Verzeichnisses „/system/modules/” und „/web/system/modules/” den Ordner der Erweiterung „multicolumnwizard” und im Verzeichnis „/vendor/” den Ordner „/menatwork/” zu löschen.

Anschließend wieder das Composer Update ausführen und die Erweiterung wurde - ohne Fehler - neu installiert.

**Comment by fritzmg** [comment]
See also

* https://community.contao.org/de/showthread.php?68308-Problem-bei-Installation-von-Bootstrap
* https://community.contao.org/de/showthread.php?68311-Fatal-Error-nach-Update-von-contao-multicolumnwizard

**Comment by fritzmg** [comment]
Der Fehler hat nichts mit dem mcw zu tun, sondern tritt auf, wenn das Composer Plugin nicht aktuell genug (war). Ab Version 3.0.8 des composer-plugin tritt das nicht mehr auf.

**Comment by zonky2** [comment]
@planepix dann kann das Ticket wieder zu - oder?
