### ISSUE TITLE
Contao 4 drag&drop problems

### ISSUE THREAD

**Issue by rabauss** [menatwork/MultiColumnWizard#227]
with version 3.3.12 in contao 4 the drag & drop wont work in prod-environment!
in dev-environment it's working - what's wrong with the js???

browser cache already cleared a few times!

**Comment by zonky2** [comment]
what is "wont work"? can you send a image or clip?

have you JS errors at your console like Firebug?

**Comment by rabauss** [comment]
unfortunately there is no js error but when i try to use the drag & drop icon (also with the arrows) nothing happens there is only a ban-sign instead of the mouse-hand.

i guess there is an error in the minified js but cannot debug...

**Comment by zonky2** [comment]
the minimized version of 3.3.11 had a bug - can you test the minimized version directly from github (3.3.12)?

**Comment by zonky2** [comment]
@rabauss I updated the minified version of javascript #228 - pls test it

**Comment by zonky2** [comment]
checked https://github.com/menatwork/MultiColumnWizard/pull/228#issuecomment-334710767

**Comment by BugBuster1701** [comment]
Das funktioniert zwar, aber nur wenn ich nach dem Update (auf dev-master) den Browser Cache lösche.
Das ist unschön. 
Wäre es da nicht sinnvoller Versionsnummern im Dateinamen zu haben damit so etwas nicht passiert?
Oder eine andere Lösung die dasselbe bewirkt?

**Comment by zonky2** [comment]
Die ganze Idee, mit dem "komrimierten Dateien" (JS, CSS) halte ich für fragwürdig - Git kann damit eigentlich nichts anfangen... Das Caching-Problem sehe ich eher bei Contao - hier sollte die min-Version beim Aufbau des int. Caches (BE) erstellt bzw. ein Timestamp oder Token angehangen werden...
