### ISSUE TITLE
Bug with new row and multiple fields like color input

### ISSUE THREAD

**Issue by zonky2** [menatwork/MultiColumnWizard#232]
Bug with new row and multiple fields e.g. with color picker

at name of new created input fields missing the array brackets

new line have `... name="mcwtest[0][mcw_text2]"...`
should have `... name="mcwtest[0][mcw_text2][]"...`

after save input mask all o.k.

**Comment by fritzmg** [comment]
I currently have the problem with contao-leads export options, that I cannot create any new rows, neither with the first (duplicate) or second (add new) `+` button. Nothing happens and there is no JavaScript error.

Is this the same issue? @zonky2 's description is not very specific ;)

**Comment by zonky2** [comment]
@fritzmg Hi - can you post the attribute name of your input field from the last row and the new row?

**Comment by fritzmg** [comment]
> pls update your MCW

This problem happens with the versions `3.3.11` and `3.3.12`. `3.3.10` works fine.

**Comment by zonky2** [comment]
at 3.3.11 Github or höhere Mächte crashed the minified js

**Comment by fritzmg** [comment]
> at 3.3.11 Github or höhere Mächte crashed the minified js

??

So a new release must/will be made?

**Comment by zonky2** [comment]
just try `dev-master (cca48dcc)`

**Comment by zonky2** [comment]
PR https://github.com/menatwork/MultiColumnWizard/pull/233
