### ISSUE TITLE
Fatal error after updating from composer

### ISSUE THREAD

**Issue by sebj54** [menatwork/MultiColumnWizard#237]
Hi! I recently updated all my modules with composer (via Contao module) and I ended up with a fatal error.

```
PHP Fatal error:  Class 'ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent' not found in /var/www/clients/client205/web1059/web/system/modules/multicolumnwizard/config/event_listeners.php on line 17
```

I solved the issue by manually adding the `contao-community-alliance/dc-general` module to my composer.json and it worked fine after that. So i thought it is just a missing dependency, am I right?

**Comment by zonky2** [comment]
should fixed with https://github.com/menatwork/MultiColumnWizard/commit/ad3353571578a374f44be4708d6258fd1ff96537

**Comment by sebj54** [comment]
Thanks for the fix, it worked :)

**Comment by zonky2** [comment]
@davidmaack can you tag a new version?
