### ISSUE TITLE
weisse Seite mit Version 3.3.11 und 3.3.12

### ISSUE THREAD

**Issue by BlackP999** [menatwork/MultiColumnWizard#238]
Nach der installation der version 3.3.11 oder 3.3.12 ist das komplette Contao "Tod".
Folgende Fehlermeldung erhalte ich:
 Fatal error: Class 'ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent' not found in .../system/modules/multicolumnwizard/config/event_listeners.php on line 17

Contao Version 3.5.26 - 3.5.30
Nach zurückstellen auf 3.3.10 geht wieder alles

**Comment by zonky2** [comment]
bitte auch die geschlossenen Tickets ansehen
https://github.com/menatwork/MultiColumnWizard/issues/237

**Comment by discordier** [comment]
[3.3.13](https://github.com/menatwork/MultiColumnWizard/releases/tag/3.3.13) ist released, Problem sollte behoben sein.

**Comment by BlackP999** [comment]
Perfekt, funktioniert wieder alles!

Danke
