### ISSUE TITLE
revert 3.3.11+ changes

### ISSUE THREAD

**Issue by fritzmg** [menatwork/MultiColumnWizard#239]
Releases `3.3.11` and `3.3.12` were broken due to

* missing minified JavaScripts
* newly added dependency to the dc-general, without adding the requirement to the `composer.json`

and thus they are unusable.

However, even tough `3.3.13` was released with the added dc-general dependency, most users will only get `3.3.12` and not higher, since there is no stable release for dc-general `2.x`. This will leave many users with either broken multicolumwizard fields or even completely broken installations once they update their packages.

**Comment by discordier** [comment]
The dependency should have never been added.
It should become a weak dependency and therefore be added to the suggests section instead.

The event listener must of course get updated along.

**Comment by zonky2** [comment]
@stefanheimes 
> This should solve a problem with the fileTree Widget or the pageTree widget.
> https://github.com/menatwork/MultiColumnWizard/commit/747bdc7d4473079d4f889a39ff5166f1b4c87ee2#commitcomment-24806245

... welches Problem sollte denn gelöst werden?

**Comment by fritzmg** [comment]
@zonky2 https://github.com/menatwork/MultiColumnWizard/issues/215

**Comment by Toflar** [comment]
Sorry but could anybody fix the releases soon? The MCW is used in so many extensions out there, please be careful when you release a new version! Right now, the minified JS is broken and I have to pin the dependency to 3.3.10 in all projects. And why the fuck is `dc-general` a dependency?

**Comment by discordier** [comment]
See #240
