### ISSUE TITLE
Hinzufügen / Duplizieren / Löschen funktioniert seit 3.3.11 nicht mehr

### ISSUE THREAD

**Issue by sebastiande** [menatwork/MultiColumnWizard#242]
Seit Version 3.3.11 funktioniert das Hinzufügen, Duplizieren & Löschen von Elementen nicht mehr. Wenn man auf die Buttons klickt passiert nichts.

In Version 3.3.10 gab es nur Hinzufügen und Löschen.

Contao Version 3.5.30

Konfiguration:

`'inputType'               => 'multiColumnWizard',			
			'eval'                    => array(
				'columnFields'	=> array
				(
					'certificate_roles'	=> array
					(
						'label'				=> &$GLOBALS['TL_LANG']['tl_role']['certificates'],
						'exclude'			=> true,
						'inputType'			=> 'select',
						'options_callback' 	=> array('tl_role', 'getCertificates'),
						'eval'				=> array('style'=>'width:360px', 'includeBlankOption'=>false, 'chosen'=>true)
					)
				),
				'buttons'		=> array('up' => false, 'down' => false), 
				'tl_class'		=> 'clr'
			),			`

**Comment by zonky2** [comment]
aktuell ist die 3.3.14
https://github.com/menatwork/MultiColumnWizard/releases 

bitte diese installieren

**Comment by sebastiande** [comment]
Es funktioniert weder in 3.3.11, 3.3.12, 3.3.13 noch in 3.3.14.

**Comment by zonky2** [comment]
bitte Prüfe/Vergleiche mal die JavaScript-Datei - ggf. Cache löschen von Contao UND Browser
