### ISSUE TITLE
inputType pageTree will not be saved

### ISSUE THREAD

**Issue by mpitz** [menatwork/MultiColumnWizard#245]
If you set up an inputType pageTree it will not be saved:

![image](https://user-images.githubusercontent.com/6831223/33597311-4744f828-d99f-11e7-85da-86bd0707a6bc.png)

**Comment by tarun-uwe** [comment]
Hi, gibt es eine Umgehungslösung, bis die Version 3.3.17 veröffentlicht wird?

**Comment by zonky2** [comment]
es gibt ja noch nicht mal einen Fix für das Problem

kurze Rückfrage: MariaDB oder MySQL 5.7 im "strict mode" ist nicht zufällig im Einsatz?

**Comment by zonky2** [comment]
Fixed in MCW-bundle https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/25
