### ISSUE TITLE
Cannot find editor configuration file "tinyMCE.php" in Contao 4.4

### ISSUE THREAD

**Issue by Samson1964** [menatwork/MultiColumnWizard#248]
Gebe ich in MCW-Feldern bei eval 'rte' =>'tinyMCE' an, so funktioniert das zwar in Contao 3.5, aber nicht in Contao 4.4. Contao stürzt mit der im Betreff genannten Fehlermeldung ab.

Im Dev-Modus gibt es Details dazu:
`
MultiColumnWizard->getMcWTinyMCEString('interview_row0_question', array('label' => null, 'exclude' => true, 'inputType' => 'textarea', 'eval' => array('rte' => 'tinyMCE', 'style' => 'width: 450px;', 'columnPos' => '1', 'required' => false, 'tl_class' => 'mcwUpdateFields', 'tableless' => true), 'activeRecord' => object(Result), 'activeRow' => 0, 'name' => 'interview[0][question]', 'id' => 'interview_row0_question', 'value' => null)) in vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php (line 610)

                        // Tiny MCE
                        if ($arrField['eval']['rte'] && strncmp($arrField['eval']['rte'], 'tiny', 4) === 0)
                        {
                            $tinyMce = $this->getMcWTinyMCEString($objWidget->id, $arrField);
                            $arrField['eval']['tl_class'] .= ' tinymce';
                        }
                        // Add custom wizard
                        if ($arrField['wizard'])
`
Zeile 610 ist:
$tinyMce = $this->getMcWTinyMCEString($objWidget->id, $arrField);

**Comment by zonky2** [comment]
https://github.com/menatwork/MultiColumnWizard/pull/246

**Comment by dmolineus** [comment]
Any news about this @zonky2  or @baumannsven?

**Comment by zonky2** [comment]
nö

**Comment by baumannsven** [comment]
Oops, that's gone down.
@zonky Can you set this issue to our bug list?

**Comment by stefanheimes** [comment]
Should be fixed in the new Bundle see https://github.com/menatwork/contao-multicolumnwizard-bundle/commit/fc49d27c97c44b4d5f6dbba417a3c8075d8e0849
