### ISSUE TITLE
Problem with Contao 4.4.17

### ISSUE THREAD

**Issue by bijeiko** [menatwork/MultiColumnWizard#253]
Hello I noticed a problem of compatibility between the module and contao 4.4.17.
Do you expect to update it in the coming month?

**Comment by zonky2** [comment]
It´s possible to post the error log or stack trace...

**Comment by bijeiko** [comment]
I do not really have any mistakes to show you.
The problem is that it does not appear in my "type of element" in the contao backend.
By cons I can give you the manipulation I did to install it

`composer require menatwork / contao-multicolumnwizard`

Then I went to `contao/install` to see if I needed to update the database. But I had nothing to update.

**Comment by discordier** [comment]
What do you mean with:
> The problem is that it does not appear in my "type of element" in the contao backend.

What is the DCA code you use to initialize the MultiColumnWizard?

**Comment by bijeiko** [comment]
What I mean is that under Contao 3, we had the option to choose Column-Set start and now we have no more options.

I do not have dca code on this module since I am on contao 4...

**Comment by zonky2** [comment]
Contao 4 continues to work with DCA files - how to reproduce the problem?

**Comment by bijeiko** [comment]
What do you mean ? and where can I find the DCA file?

I do not know how you can reproduce the problem apart from reinstalling contao 4 and the module

**Comment by bijeiko** [comment]
I'm coming back to you ... here I have to apologize for making you waste time I stumbled on a untruc which finally was not the right module xD

Sorry again
