### ISSUE TITLE
Field "..." does not exist in DCA

### ISSUE THREAD

**Issue by paha77** [menatwork/MultiColumnWizard#257]
Wir haben ein eigenes Modul in Contao 3.5, das wir im **Contao 4.4** installieren wollen.

In der DCA wird MCW so verwendet:

```php
            'eval' 			    => array (
                'columnFields' => array
                (
                    'uploadFolder' => array
                    (
                        'label'                 => "test",
                        'exclude'               => true,
                        'inputType'             => 'fileTree',
                        'eval'                  => array('fieldType'=>'radio', 'tl_class'=>'clr', 'path'=>'files/images'),
      
                    )
                )
            )

```

Wen wir einen Ordner im FileTree auswählen, kommt der AJAX-Request im Hintergrund mit einem 400er Fehler und im System-Log steht:

```Field .." does not exist in DCA...```

Ich habe ein bisschen rechechiert, in Contao\Ajax.php wird dieses dynamisches MCW-Feld nicht gefunden, weil die MultiColumnWizardHelper::supportModalSelector() den DCA wegen dem geänderten Backend-URL (nicht contao/file.php oder contao/page.php sondern contao/files?do=files&popup=1&picker=... ) nicht ändert.

**Comment by stefanheimes** [comment]
See #258

**Comment by stefanheimes** [comment]
Should be fixed in the new bundle see https://github.com/menatwork/contao-multicolumnwizard-bundle
