### ISSUE TITLE
colorpicker and contao 4

### ISSUE THREAD

**Issue by arboc** [menatwork/MultiColumnWizard#259]
In `MultiColumnWizard/system/modules/multicolumnwizard/MultiColumnWizard.php` is a wrong path to the colorpicker assets.

Instead of line 597:
```
imgPath: "assets/mootools/colorpicker/' . $GLOBALS['TL_ASSETS']['COLORPICKER'] . '/images/",
```
it must be
```
imgPath: "assets/colorpicker/' . $GLOBALS['TL_ASSETS']['COLORPICKER'] . '/images/",
```

**Comment by stefanheimes** [comment]
Fixed in the new bundle see https://github.com/menatwork/contao-multicolumnwizard-bundle/commit/6961cf449e57659a4f9de39d7cfb11420c167cf2
