### ISSUE TITLE
app_dev Exception: non-existent service

### ISSUE THREAD

**Issue by Xendiadyon** [menatwork/MultiColumnWizard#262]
Hello,
in a rather complex projekt (Contao 4.4.33 with Metamodels 2.1 and a lot of other extensions), I tried to access the Simfony Profiler via the app_dev.php

When opening the app_dev.php, a Contao-Error is triggered.
Using the Simfony Profiler error trace, I can see the following exception:
`You have requested a non-existent service "maw.mcw.events.listener.initialize_system".`
in vendor/menatwork/contao-multicolumnwizard-bundle/legacy_layer/classmap/MultiColumnWizardHelper.php (line 132)

line 132
`$helper = \System::getContainer()->get($serviceName);`
and $serviceName is (of course):
`$serviceName = 'maw.mcw.events.listener.initialize_system';`

Probably, we have an extension "somewhere" which uses the TL_HOOK "initializeSystem".
In general, this should be no problem. But somehow the execution of the initializeSystem Hook leads to an error.
The reason why the $serviceName 'maw.mcw.events.listener.initialize_system' is not found is unclear to me.
I suppose it is not an issue with the extension (whatever-it-is) which uses the Hook, but with MultiColumnWizard.

Could you please check if this service exists?

**Comment by zonky2** [comment]
you add the MCW bundle at your composer.json?

see https://github.com/MetaModels/core/issues/1260

**Comment by discordier** [comment]
If so, did you clear the cache? The service got renamed for the bundle from 
`maw.mcw.events.listener.initialize_system` to
`menatwork.multicolumnwizard-bundle.events_listener.initialize_system`

Clearing the cache (`rm -rf var/cache/{prod,dev}`) should fix this.

**Comment by Xendiadyon** [comment]
Thank you. Clearing the cache already did the job.
