### ISSUE TITLE
Keine Frontendfunktionalität in Contao 4, Template form_widget nicht mehr vorhanden

### ISSUE THREAD

**Issue by theDyingMountain** [menatwork/MultiColumnWizard#263]
Das Template form_widget ist seit Contao 4 nicht mehr vorhanden, dadurch kann der MCW im Frontend nicht mehr verwendet werden:

https://github.com/menatwork/MultiColumnWizard/blob/da92637bb9f7b305baf09748c2f6aa83cd84f057/system/modules/multicolumnwizard/MultiColumnWizard.php#L102

**Comment by BugBuster1701** [comment]
Aus der Readme:

> At Contao 4 use the MCW bundle - see https://github.com/menatwork/contao-multicolumnwizard-bundle

**Comment by zonky2** [comment]
wrong repository
