### ISSUE TITLE
Operations-Buttons werden nicht gefunden

### ISSUE THREAD

**Issue by Samson1964** [menatwork/MultiColumnWizard#265]
In Contao 4.8 funktionieren einige der Buttons nicht, weil sie im Theme flexible nicht mehr vorhanden sind. move und new werden angezeigt, weil es z.B. system/themes/flexible/icons/new.svg gibt. Die Icons für up, down, copy und delete gibt es nicht als SVG, dafür aber als GIF.
Ersatzweise gebe ich die GIF-Grafiken an.

**Comment by zonky2** [comment]
für Contao 4 sollte das Bundle einegesetzt werden: https://github.com/menatwork/contao-multicolumnwizard-bundle - Issues bitte dort
