### ISSUE TITLE
Wizard funktioniert im FF nicht

### ISSUE THREAD

**Issue by Toflar** [menatwork/MultiColumnWizard#36]
Irgendwie fehlt das preventDefault() oder sowas. Beim Firefox (Chrome geht witzigerweise) werde ich beim Klick aufs "+" auf den entsprechenden Link weitergeleitet und krieg dann n 404 Not Found.

Kann das jemand bestätigen? Den Fehler konnte ich aber nicht finden, deshalb mach ich mal n Issue und hoffe auf Hilfe :S

**Comment by zonky2** [comment]
in den gängigen Browsern sind mir keine Fehler bekannt @Toflar bitte wieder öffnen, sofern das (wieder) auftaucht...
