### ISSUE TITLE
Neue-Zeile Button

### ISSUE THREAD

**Issue by psi-4ward** [menatwork/MultiColumnWizard#38]
Wäre schön wenn man einen "neue Zeile" Button hätte um nicht jedesmal die Inhalte löschen zu müssen.

**Comment by garyee** [comment]
Ich fände das auch gut!

**Comment by zonky2** [comment]
ist im PR https://github.com/menatwork/MultiColumnWizard/pull/219 mit enthalten

**Comment by zonky2** [comment]
in https://github.com/menatwork/MultiColumnWizard/releases/tag/3.3.11 enthalten
