### ISSUE TITLE
Gruppierung von Elementen

### ISSUE THREAD

**Issue by may17** [menatwork/MultiColumnWizard#60]
Moin,

entweder ich hab das mit der Gruppierung nicht verstanden oder es ist ein Fehler.

Ich habe 10 Elemente und möchte diese in zwei spalten jeweils aufbauen. Hierfür wäre die Gruppierung geeignet da die Labels dadurch überhalb der Inputfelder stehen und nicht im table head.

Jetzt kommt bei einigen die Frage warum ich das überhaupt will? Ganz einfach ich hab einen Slider gebaut und will die config in einem blob speichern. Wenn ich die Buttons des MultiColumnWizard deaktiviere klappt das auch ganz gut.

Nun zu dem Problem. Gruppiere ich nun 2 elemente jeweils mit row_1, row_2 usw. wird nur das erste label ausgegeben. Die anderen sind leer.

Ich möchte nicht ausschließen das mein Ansatz hier der falsche ist und es sich um einen Benutzerfehler handelt. Falls das so ist, wäre es schön wenn man die Option hätte die labels entweder im table head oder überhalb der Felder auszugeben.

vg joe

**Comment by zonky2** [comment]
@may17 ich verstehe die Sache auch nicht - kannst Du Dein DCA-Snippet mal einstellen und ggf. kleinen Screenshot, wie Du Dir die Sache wünschst

**Comment by may17** [comment]
Ähm, das ist nun 5 Jahre her. Ich denke das kann einfach zu :)

**Comment by zonky2** [comment]
o.k.!
