### ISSUE TITLE
D&D : Radio wird falsch angezeigt

### ISSUE THREAD

**Issue by lindesbs** [menatwork/MultiColumnWizard#77]
Drag&Drop aktiviert, Mehrzeilige Liste mit einem Radio Field

Wahrend Dragging alles ok. Nach dem Drop ist die Zeile NACH der eingefuegten mit einem nicht initialisierten RadioList (d.h. leer) obwohl vorher die Zeile gefuellt war.

**Comment by zonky2** [comment]
Über die Methode `updateRowAttributes`beim D&D werden die Zeilen-Nummern in Name-Attribut neu gesetzt - da das für jedes Element sequentiell gemacht wird, haben die zwei Checkbox-Zeilen, die getauscht werden irgendwann die selben "Namen-Keys" - der Browser wirft automatisch das checked raus.... im Firebug & Co. ist das checked noch zu sehen.

Das wird man wahrscheinlich nur umgehen können, wenn man beim D&D von Radiobuttons vorher den checked-Wert zwischenspeichert (z.B. als data) und bei complete wieder zuweist und entfernt.

**Comment by zonky2** [comment]
Fixed MCW-bundle https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/25
