### ISSUE TITLE
options_callback in prepareForWidget()-Problematik

### ISSUE THREAD

**Issue by Toflar** [menatwork/MultiColumnWizard#85]
Hey Jungs

Ich glaub ihr habt hier (https://github.com/menatwork/MultiColumnWizard/blob/master/system/modules/multicolumnwizard/MultiColumnWizard.php#L833) die gleiche Problematik wie ich in diesem Ticket: https://github.com/aschempp/contao-calendar_memberregistration/issues/1

Irgend einen Lösungsansatz?

**Comment by zonky2** [comment]
@Toflar ist das irgendwie noch aktuell
