### ISSUE TITLE
Label-Position nicht korrekt

### ISSUE THREAD

**Issue by aschempp** [menatwork/MultiColumnWizard#93]
Ich verwende 3.1.0 beta2. Meine Konfiguration sieht folgendermassen aus:

``` php
'columnFields' => array
(
    'value' => array
    (
        'label'     => &$GLOBALS['TL_LANG']['tl_iso_attributes']['options']['value'],
        'inputType' => 'text',
        'eval'      => array('class'=>'tl_text_2'),
    ),
    'label' => array
    (
        'label'     => &$GLOBALS['TL_LANG']['tl_iso_attributes']['options']['label'],
        'inputType' => 'text',
        'eval'      => array('class'=>'tl_text_2'),
    ),
    'default' => array
    (
        'label'     => &$GLOBALS['TL_LANG']['tl_iso_attributes']['options']['default'],
        'inputType' => 'checkbox',
        'eval'      => array('columnPos'=>2),
    ),
    'group' => array
    (
        'label'     => &$GLOBALS['TL_LANG']['tl_iso_attributes']['options']['group'],
        'inputType' => 'checkbox',
        'eval'      => array('columnPos'=>3),
    ),
),
```

Für die beiden Checkboxen soll kein Spalten-Titel angezeigt werden, sondern jeweils der Label. Das funktioniert grundsätzlich. Allerdings ist der Label des Feld 2 an der falschen Position (siehe screenshot).
![Bildschirmfoto 2013-01-29 um 18 27 32](https://f.cloud.github.com/assets/1073273/107810/3747e79e-6a39-11e2-9b4f-7594916c9698.png)

**Comment by zonky2** [comment]
ist der immer noch "offen"?

**Comment by zonky2** [comment]
Test mit 3.3.12:

=> tritt nicht mehr auf

![shot364](https://user-images.githubusercontent.com/1045318/31279524-a140cc00-aaa9-11e7-8827-2d78223bace1.jpg)

**Comment by zonky2** [comment]
@aschempp der Warnhinweis im Iso-Handbuch könnte somit wieder raus

**Comment by aschempp** [comment]
Das ginge dann wohl an @netzarbeiter 😉

**Comment by zonky2** [comment]
@aschempp macht den @netzarbeiter das Isotope-Handbuch??

**Comment by aschempp** [comment]
https://isotopeecommerce.org/de/team.html 😉

**Comment by zonky2** [comment]
alles klaro! ;-)

**Comment by netzarbeiter** [comment]
Der Warnhinweis im Handbuch wurde auf folgenden Seiten entfernt:
- https://isotopeecommerce.org/de/handbuch/v/2.5/r/select-menue.html
- https://isotopeecommerce.org/de/handbuch/v/2.5/r/checkbox-menue.html
