### ISSUE TITLE
MCW im Frontend - Fehler

### ISSUE THREAD

**Issue by DrKnutsen** [menatwork/MultiColumnWizard#94]
Moin Moin aus Hamburg,
ich habe ein kleines (grosses?) Problem mit dem MCW in einem Formular im Frontend und finde den Fehler nicht. Duplizieren und Löschen funktioniert nur mit der ersten Reihe eines MCW. Danach scheint das JS die Klick-Events nicht mehr zu unterbinden und ich lande auf:
index.php?&amp;cmd_=copy&amp;cid=0&amp;id=
Wie man am Link sieht, fehlt auch der Feldbezeichner hinter "cmd_" - das es keine ID gibt, ok bin ja im FE...
Ist der MCW überhaupt fürs Frontend gedacht? Ist wohl irgendein JS Problem, aber ich blicke da nicht durch :/
Ach so: Contao 2.11.6 und MCW 3.0
Weiss jemand was?
Beste Grüsse, K

**Comment by vmulot** [comment]
Any news on this pb ? go the same one.
thanks :)

**Comment by discordier** [comment]
As it is in pending state. Nope, We simply do not have the time right now to tackle this.

Feel free to send an PR or hire someone to fix it and send an PR then though.

**Comment by zonky2** [comment]
pls check https://github.com/richardhj/contao-multicolumnwizard-frontend
