### ISSUE TITLE
MultiColumnWizard field including a TextStore field does not work as expected

### ISSUE THREAD

**Issue by globalcow** [menatwork/MultiColumnWizard#95]
Environment: Contao 2.11.9 and the MultiColumnWizard from ER

If a TextStore field is included in a MultiColumnWizard Field the value is stored properly the first time the container is saved. If the container is saved again without changing the value inside the TextStore field, the value is overwritten with an empty value.

This is a different behavior compared to the SMTP password field in the general Contao settings. The password will not be overwritten if the settings are saved again.

Normally the TextStore field ignores the input if nothing changed: blnSubmitInput = false
However, the MultiColumnWizard will not handle this case.

**Comment by zonky2** [comment]
checked with 3.3.12:

this field works fine

![shot365](https://user-images.githubusercontent.com/1045318/31280216-f2b3effc-aaab-11e7-9bc0-e31e330f4f87.jpg)

and for save only after a new input, you should work with your own save_callback
